use_frameworks!

platform :ios, '11.0'

target 'MiCard_Example' do
  pod 'MiCard', :path => '../'

  target 'MiCard_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
